from PIL import Image, ImageOps
from PIL.Image import Resampling
import PySimpleGUI as psg
#import sys
import os
import WorkPiece
from typing import NamedTuple

class Pixel(NamedTuple):
    red: int
    green: int
    blue: int
    alpha: int

class ContourElement(NamedTuple):
    start: int
    length: int
    height: int

    def __str__(self):
        return f'{self.start = } {self.length = } {self.height = }'

class ContourLine:
    def __init__(self, y: float):
        self.y: float = y
        self.contour_elements: list[ContourElement] = []

    def __str__(self):
        return f'{self.contour_elements = }'

    def __len__(self):
        return len(self.contour_elements)

    def __getitem__(self, key: int):
        if key < 0 or key > len(self.contour_elements):
            raise KeyError(f'Invalid key {key}, should be between 0 and {len(self.contour_elements)}')
        return self.contour_elements[key]

    def append(self, start: int, length: int, height: int):
        self.contour_elements.append(ContourElement(start, length, height))

class Bit:
    def __init__(self, type: str, diameter: float):
        self.type = type
        self.diameter = diameter

    def __str__(self):
        return f'{self.type} {self.diameter}mm'
    
    def radius(self):
        return self.diameter / 2

class VCutWorkDetail:
#    ALPHA = 3

    def __init__(self,
                 image,
                 carve_width: float,
                 carve_height: float,
                 bit: Bit,
                 carve_track_width: float = 0.2,
                 feature_depth: float = 3.0,
                 feed_rate: float = 300.0,
                 fly_rate: float = 1500.0):
        self.bit = bit

        self.image = image

        self.carve_width = carve_width
        self.carve_height = carve_height
        self.carve_track_width = carve_track_width
        self.z_feature_cut_depth = feature_depth
        self.z_maximum = self.z_feature_cut_depth
        self.z_feature_stride = self.z_feature_cut_depth / 255
        self.feed_rate = feed_rate
        self.fly_rate = fly_rate

        self.z_steps = 255
        self.z_stride = self.z_feature_cut_depth / self.z_steps

        self.work_image = self.image.resize((int(self.carve_width / self.carve_track_width + 0.5), int(self.carve_height / self.carve_track_width + 0.5)), Resampling.NEAREST)
        self.work_image = ImageOps.flip(self.work_image)

        self.mm_per_pixel = self.carve_width / self.work_image.width

        self.contours: list[ContourLine] = []

        self.gcode: list[str] = []

    def generate_contours(self) -> None:
        for y in range(self.work_image.height):
            contour_line = ContourLine(y * self.mm_per_pixel)
            self.contours.append(contour_line)
            pixel = Pixel(*self.work_image.getpixel((0, y))) # type: ignore
            cur_height = pixel_to_height(pixel)
            start_x = 0
            for x in range(self.work_image.width):
                pixel = Pixel(*self.work_image.getpixel((x, y))) # type: ignore
                next_height = pixel_to_height(pixel)
                if next_height != cur_height:
                    contour_line.append(start_x, x - start_x, cur_height)
                    cur_height = next_height
                    start_x = x
            else:
                # process the last one
                contour_line.append(start_x, x - start_x, cur_height) # type: ignore

    def generate_gcode(self) -> None:
        self.gcode = []

        work = WorkPiece.WorkPiece('PNGAlpha2NC.nc',
                                   creator = 'Generated by PNGAlpga2NC.py',
                                   material = 'MDF',
                                   feed_rate = self.feed_rate,
                                   fly_rate = self.fly_rate,
                                   thickness = 12,
                                   units = 'mm',
                                   bit = WorkPiece.Bit(self.bit.type, self.bit.diameter) )
        self.gcode += work.gcode_header()
        self.gcode.append(';')
        self.gcode.append('; Spindle is centered on work piece')

        # x and y start are different because offsets because the y will always
        # be moved BEFORE the first plunge but the x will only move AFTER the
        # first plunge
        x_start = -((self.carve_width / 2) - (self.carve_track_width / 2))
        y_start = -((self.carve_height / 2) + (self.carve_track_width / 2))

        self.gcode += work.gcode_safe_z()

        # Start point is bottom left
        self.gcode += work.gcode_move_xy(x = x_start, y = y_start, comment = 'Start position allowing for bit to move relative for first contour')

        left_to_right = True
        for contour in self.contours:
            segments = len(contour)

            # if just one segment and no cutting just move up the Y axis
            if segments == 1 and contour[0].height == 0:
                self.gcode += work.gcode_safe_z()
                self.gcode += work.gcode_move_relative_xy(y = self.mm_per_pixel, comment = f'Start of contour {left_to_right = }')
            else:
                self.gcode += work.gcode_safe_z()
                self.gcode += work.gcode_move_relative_xy(y = self.mm_per_pixel, comment = f'Start of contour {left_to_right = }')

                if left_to_right:
                    for segment in range(segments):
                        # if last segment and flying (not cutting) just ignore the move
                        if segment == segments - 1 and contour[segment].height == 0:
                            self.gcode += work.gcode_move_z(2)
                            self.gcode += work.gcode_fake_move_relative_xy(x = contour[segment].length * self.mm_per_pixel, flying = True)
                            continue
                        if contour[segment].height:
                            self.gcode += work.gcode_move_z(-(self.z_feature_stride * contour[segment].height))
                            self.gcode += work.gcode_move_relative_xy(x = contour[segment].length * self.mm_per_pixel)
                        else:
                            self.gcode += work.gcode_move_z(2)
                            self.gcode += work.gcode_move_relative_xy(x = contour[segment].length * self.mm_per_pixel, flying = True)
                else:
                    for segment in range(segments - 1, -1, -1):
                        # if first segment and flying (not cutting) just ignore the move
                        if segment == 0 and contour[segment].height == 0:
                            self.gcode += work.gcode_move_z(2)
                            self.gcode += work.gcode_fake_move_relative_xy(x = -(contour[segment].length * self.mm_per_pixel), flying = True)
                            continue
                        if contour[segment].height:
                            self.gcode += work.gcode_move_z(-(self.z_feature_stride * contour[segment].height))
                            self.gcode += work.gcode_move_relative_xy(x = -(contour[segment].length * self.mm_per_pixel))
                        else:
                            self.gcode += work.gcode_move_z(2)
                            self.gcode += work.gcode_move_relative_xy(x = -(contour[segment].length * self.mm_per_pixel), flying = True)

                left_to_right = not left_to_right

        self.gcode += work.gcode_trailer()

    def write_gcode_file(self, file_name: str) -> None:
        outfile = open(file_name, 'w')
        print('\n'.join(self.gcode), file = outfile)
        outfile.close()

def pixel_to_height(pixel: Pixel) -> int:
    # If there is any alpha that is a CUT
    return pixel.alpha

def get_float(text: str, default: str = '', min: float | None = None, max: float | None = None) -> float:
    while True:
        value = psg.popup_get_text(text, default_text = default)
        if value is None:
            exit()
        try:
            value = float(value)
        except ValueError:
            psg.popup_timed('Enter a floating point number', auto_close_duration = 5)
            continue
        if min and value < min:
            psg.popup_timed(f'Value must be greater or equal to {min}', auto_close_duration = 5)
        if max and value > max:
            psg.popup_timed(f'Value must be less than or equal to {max}', auto_close_duration = 5)
    return value

print('Convert a skyline silhouette to NC')
print('Size of workpiece should be a 16/9 ratio')

png_file = psg.popup_get_file('Select hight map image', file_types = (('PNG Files', '*.png'),))

img = Image.open(png_file)
img.load()

bit = Bit('20 degree V-bit', 0.5)

carve_width = get_float('Carve width (x-axis mm)')
carve_height = get_float('Carve height (y-axis mm)')
z_feature_cut_depth = get_float('Z maximum cut depth for features (mm)', default = '5')
feed_rate = get_float('Feed rate (mm per minute)', default = '300.0', min = 100.0, max = 750.0)
fly_rate = get_float('Fly rate (mm per minute)', default = '1500.0', min = 300.0, max = 2000.0)

work_detail = VCutWorkDetail(img,
                             carve_width,
                             carve_height,
                             bit,
                             carve_track_width = 0.2,
                             feature_depth = z_feature_cut_depth,
                             feed_rate = feed_rate,
                             fly_rate = fly_rate)

work_detail.generate_contours()

work_detail.generate_gcode()

nc_file_path = os.path.splitext(png_file)[0] + '.nc'

nc_file = psg.popup_get_file('Generated gcode', save_as = True, default_extension = '.nc', default_path = nc_file_path, file_types = (('GCode', '.nc'),))
work_detail.write_gcode_file(nc_file)