from datetime import datetime, timezone

MM = 0
INCHES = 1

def _unit_size(size: float, units: int) -> str:
    value = f'{size:.2f}'
    if units == MM:
        value += 'mm'
    elif units == INCHES:
        value += ' inches'
    else:
        value += '???'

    return value


class Bit():
    def __init__(self, type: str = 'double flute straight end mill', diameter: float = 3.175, units: str = 'mm'):
        self.type = type
        self.diameter = diameter
        if units.lower() in ('mm', 'millimeters'):
            self.units = MM
        else:
            self.units = INCHES

    def __str__(self) -> str:
        return f'{_unit_size(self.diameter, self.units)} {self.type}'

class WorkPiece():
    def __init__(self,
                 output_file: str,
                 creator: str = 'Generated by script',
                 material: str = 'plywood',
                 thickness: float = 9.0,
                 units: str = 'mm',
                 safe_height: float = 3.0,
                 plunge_rate: float = 225.0,
                 feed_rate: float = 750.0,
                 fly_rate: float = 1500.0,
                 spindle_speed: int = 10000,
                 bit: Bit | None = None):
        self.output_file = output_file
        self.creator = creator
        self.material = material
        self.thickness = thickness
        if units.lower() in ('mm', 'millimeters'):
            self.units = MM
        else:
            self.units = INCHES
        self.safe_height = safe_height
        self.plunge_rate = plunge_rate
        self.feed_rate = feed_rate
        self.fly_rate = fly_rate
        self.spindle_speed = spindle_speed

        if bit is not None:
            self.bit = bit
        else:
            self.bit = Bit(units = units)
        if self.bit.units != self.units:
            raise ValueError(f'Bit units do mot match material units')

        self.x = 0.0
        self.y = 0.0
        self.z = 0.0

        self.lines = []

    def gcode_header(self) -> list:
        now = datetime.now()
        lines = []
        lines.append(f'; Generated: {now}')
        lines.append(f'; Creator: {self.creator}')
        lines.append(';')
        lines.append(f'; Material: {_unit_size(self.thickness, self.units)} {self.material}')
        lines.append(f'; Bit: {self.bit}')
        lines.append(';')
        lines.append(f'; Safe height: {_unit_size(self.safe_height, self.units)}')
        lines.append(f'; Plunge rate: {_unit_size(self.plunge_rate, self.units)}/minute')
        lines.append(f'; Feed rate: {_unit_size(self.feed_rate, self.units)}/minute')
        lines.append(f'; Fly rate: {_unit_size(self.fly_rate, self.units)}/minute')
        lines.append(f'; Spindle speed: {self.spindle_speed:,} RPM')
        lines.append(';')
        lines.append('; Header')
        if self.units == MM:
            lines.append(f'G21 ; set units to millimeters')
        elif self.units == INCHES:
            lines.append(f'G20 ; set units to inches')
        else:
            raise RuntimeError(f'Invalid units {self.units} in gcode_header()')
        lines.append('G90 ; absolute positioning')
        lines.append(f'M3 S{self.spindle_speed} ; spindle start')
        lines += self.gcode_safe_z()

        return lines

    def gcode_trailer(self) -> list:
        lines = []
        lines.append('; Trailer')
        lines += self.gcode_safe_z()
        lines.append('G0 X0 Y0 ; home')
#        lines.append('G4 P100 ; pause ')
        lines.append('M5 ; spindle stop')
#        lines.append('G4 P100 ; pause ')

        return lines

    def gcode_move_xy(self, x: float | None = None, y: float | None = None, flying:bool = False, comment: str | None = None) -> list:
        lines = []

        if x is not None or y is not None:
            line = 'G1'
            if x is not None:
                line += f' X{x:.3f}'
                self.x = x
            if y is not None:
                line += f' Y{y:.3f}'
                self.y = y
            if flying:
                line += f' F{self.fly_rate}'
            else:
                line += f' F{self.feed_rate}'
            if comment is not None:
                line += f' ; {comment}'
            lines.append(line)

        return lines

    def gcode_fake_move_xy(self, x: float | None = None, y: float | None = None, flying:bool = False, comment: str | None = None) -> list:
        lines = []

        if x is not None or y is not None:
#            line = 'G1'
            line = ''
            if x is not None:
#                line += f' X{x:.3f}'
                self.x = x
            if y is not None:
#                line += f' Y{y:.3f}'
                self.y = y
#            if flying:
#                line += f' F{self.fly_rate}'
#            else:
#                line += f' F{self.feed_rate}'
            if comment is not None:
                line += f'; {comment}'
            if line != '':
                lines.append(line)

        return lines

    def gcode_move_xyz(self, x: float | None = None, y: float | None = None, z: float | None = None, comment: str | None = None) -> list:
        lines = []

        if x is not None or y is not None or z is not None:
            line = 'G1'
            if x is not None:
                line += f' X{x:.3f}'
                self.x = x
            if y is not None:
                line += f' Y{y:.3f}'
                self.y = y
            if z is not None:
                line += f' Z{z:.3f}'
                self.z = z
            line += f' F{self.feed_rate}'
            if comment is not None:
                line += f' ; {comment}'
#            print(f'{line = }')
            lines.append(line)

        return lines

    def gcode_move_relative_xy(self, x: float | None = None, y: float | None = None, flying:bool = False, comment: str | None = None) -> list:
        to_x = x
        to_y = y

        if x is not None:
            to_x = self.x + x

        if y is not None:
            to_y = self.y + y

        return self.gcode_move_xy(to_x, to_y, flying, comment)

    def gcode_fake_move_relative_xy(self, x: float | None = None, y: float | None = None, flying:bool = False, comment: str | None = None) -> list:
        to_x = x
        to_y = y

        if x is not None:
            to_x = self.x + x

        if y is not None:
            to_y = self.y + y

        return self.gcode_fake_move_xy(to_x, to_y, flying, comment)

    def gcode_move_relative_xyz(self, x: float | None = None, y: float | None = None, z: float | None = None, comment: str | None = None) -> list:
        to_x = x
        to_y = y
        to_z = z

        if x is not None:
            to_x = self.x + x

        if y is not None:
            to_y = self.y + y

        if z is not None:
            to_z = self.z + z

        return self.gcode_move_xyz(to_x, to_y, to_z, comment)

    # Special X and Y are relative, Z is absolute
    def gcode_move_relative_xy_z(self, x: float | None = None, y: float | None = None, z: float | None = None, comment: str | None = None) -> list:
        to_x = x
        to_y = y
        to_z = z

        if x is not None:
            to_x = self.x + x

        if y is not None:
            to_y = self.y + y

        if z is not None:
            to_z = z

#        print(f'{to_x = } {to_y = } {to_z = }')
        return self.gcode_move_xyz(to_x, to_y, to_z, comment)

    def gcode_move_z(self, z: float | None = None, comment: str | None = None) -> list:
        lines = []

        if z is not None:
            line = f'G1 Z{z:.3f} F{self.plunge_rate:.3f}'
            if comment is not None:
                line += f' ; {comment}'
            lines.append(line)
            self.z = z

        return lines

    def gcode_move_relative_z(self, z: float | None = None, comment: str | None = None) -> list:
        to_z = z

        if z is not None:
            to_z = self.z + z

        return self.gcode_move_z(to_z, comment)

    def gcode_safe_z(self) ->list:
        lines = []
        lines.append(f'G1 Z{self.safe_height:.3f} F{self.plunge_rate:.3f} ; safe height')
        self.z = self.safe_height

        return lines

    def output(self, lines: list | None = None):
        file = open(self.output_file, 'w')

        if lines is None:
            lines = self.lines

        print('\n'.join(lines), file = file)
        file.close()

if __name__ == '__main__':
    work = WorkPiece('WorkPiece.nc', 'Testing')
    work.lines += work.gcode_header()
    work.lines += work.gcode_move_xy(10, 15, comment = 'move to next object')
    work.lines += work.gcode_move_z(0, comment = 'cut rectangle')
    work.lines += work.gcode_move_relative_z(-0.5)
    work.lines += work.gcode_move_relative_xy(x = 5)
    work.lines += work.gcode_move_relative_xy(y = 5)
    work.lines += work.gcode_move_relative_xy(x = -5)
    work.lines += work.gcode_move_relative_xy(y = -5)
    work.lines += work.gcode_move_relative_z(-0.5)
    work.lines += work.gcode_move_relative_xy(x = 5)
    work.lines += work.gcode_move_relative_xy(y = 5)
    work.lines += work.gcode_move_relative_xy(x = -5)
    work.lines += work.gcode_move_relative_xy(y = -5)
    work.lines += work.gcode_safe_z()
    work.lines += work.gcode_trailer()
    print(f'{work.lines}')
    work.output()